### ISSUE TITLE
Add more visualization

### ISSUE THREAD

**Issue by haidycanilao** [aelluminate/gym-members-exercise-analysis#2]
Other visualizations aren't yet implemented. Here are the following visualizations that needed to be shown:

- Calories Burned By Session Duration And Experience Level

**Comment by teammnemora** [comment]
Refactored and added new analysis:

**Refactored**
- Weight vs. BMI Analysis
  - Categorized them by Age Group & Gender
- Calories Burned Analysis
  - Categorized them by Different Workouts & Session Duration based on Gender

**Added**
- Heart Rate Analysis
- Water Intake Analysis
